# Generated by Django 5.2.7 on 2026-01-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-creared_at',)},
        ),
    ]
